### ISSUE TITLE
Output Improvements

### ISSUE THREAD

**Issue by DSdatsme** [HarshKapadia2/dotfiles#1]
Throughout the setup script, you are using stdouts like the following
```bash
echo "";
echo "NOTE: Ignoring invalid argument $1.";
echo "";
```

You can use a method call and pass on your output string to it as an argument, this will 
- save a lot of lines
- adds consistency
- Easier maintenance if you want to change output format

**Comment by HarshKapadia2** [comment]
I get what you're saying, but I think a method call for this is overkill.

What if I just used `printf` instead?

So instead of 

```bash
echo "";
echo "NOTE: Ignoring invalid argument $1.";
echo "";
```

I would write

```bash
printf "\nNOTE: Ignoring invalid argument $1.\n";
```

Cc: @KartikSoneji

**Comment by KartikSoneji** [comment]
Note that string literals can span multiple lines.

```sh
echo "
NOTE: Ignoring invalid argument $1.

";
```

Also, this depends on how big the script grows.
The overhead of a method call is negligible, readability is more important
